version: '3.9'

services:
  db:
    container_name: postgres-expense-test
    image: postgres:14.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/expenses_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=expenses_db

  migration:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; 
      npx prisma migrate deploy && echo "Migrations applied ✅, Test environment 🧪 " && exit 0'
    depends_on:
      - db
